import { StyleSheet, Platform } from "react-native";
import { green, ink, muted } from "../theme/colors";

export const s = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: "#FAFBF7",
    flexDirection: "row",
    paddingTop: Platform.OS === "android" ? 28 : 0,
  },
  sidebar: {
    width: 240,
    backgroundColor: "#fff",
    borderRightWidth: 1,
    borderColor: "#E8ECE4",
    padding: 25,
    paddingTop: 34,
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 10 },
  logo: {
    backgroundColor: green,
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  brandText: {
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: -1.5,
    color: green,
  },
  sidebarCaption: {
    fontSize: 8,
    letterSpacing: 1.3,
    color: muted,
    marginTop: 12,
  },
  navItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 10,
  },
  navActive: { backgroundColor: "#EDF3E8" },
  navText: { fontSize: 14, color: muted },
  farmNote: {
    backgroundColor: "#F4F6EC",
    borderRadius: 15,
    padding: 17,
    gap: 12,
    marginBottom: 24,
  },
  profile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderTopWidth: 1,
    borderColor: "#E9ECE5",
    paddingTop: 22,
    marginTop: 14,
  },
  avatar: {
    backgroundColor: "#F1E9D8",
    width: 37,
    height: 37,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  topbar: {
    height: 91,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderColor: "#E8ECE4",
    paddingHorizontal: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 10 },
  eyebrow: { fontSize: 9, color: muted, letterSpacing: 1.2, marginBottom: 5 },
  label: { fontSize: 13, fontWeight: "600", color: ink },
  iconButton: { padding: 8, borderRadius: 20 },
  basketButton: {
    backgroundColor: green,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 15,
    flexDirection: "row",
    gap: 9,
    alignItems: "center",
  },
  content: {
    paddingBottom: 35,
    maxWidth: 1440,
    width: "100%",
    alignSelf: "center",
  },
  between: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  breadcrumb: { fontSize: 11, color: muted, marginBottom: 4 },
  link: { fontSize: 12, fontWeight: "600", color: green },
  hero: {
    minHeight: 292,
    borderRadius: 18,
    overflow: "hidden",
    marginTop: 23,
    backgroundColor: green,
  },
  heroShade: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(12,40,24,0.56)",
  },
  heroContent: { padding: 30, alignItems: "flex-start" },
  heroEyebrow: {
    color: "#E0E9C4",
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: "600",
  },
  heroTitle: {
    color: "#fff",
    fontWeight: "700",
    letterSpacing: -1.5,
    marginTop: 13,
  },
  heroSub: {
    fontSize: 12,
    color: "#E9EDDF",
    marginTop: 12,
    maxWidth: 310,
    lineHeight: 20,
  },
  heroButton: {
    backgroundColor: "#F3F3D9",
    borderRadius: 8,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    marginTop: 20,
  },
  heroStamp: {
    position: "absolute",
    right: 24,
    bottom: 25,
    width: 80,
    height: 80,
    borderWidth: 1,
    borderColor: "#C9D3BC",
    borderRadius: 45,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#45644599",
  },
  stampText: {
    fontSize: 8,
    letterSpacing: 1,
    color: "#fff",
    textAlign: "center",
    lineHeight: 13,
  },
  benefits: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 15,
    paddingVertical: 25,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderColor: "#E6EADF",
  },
  benefit: { flexDirection: "row", alignItems: "center", gap: 11 },
  benefitIcon: {
    width: 39,
    height: 39,
    borderRadius: 20,
    backgroundColor: "#EFF3E7",
    alignItems: "center",
    justifyContent: "center",
  },
  heading: { fontSize: 24, fontWeight: "700", color: ink, letterSpacing: -0.7 },
  muted: { fontSize: 12, color: muted, lineHeight: 19 },
  search: {
    flex: 1,
    minWidth: 180,
    borderWidth: 1,
    borderColor: "#E2E7DD",
    backgroundColor: "#fff",
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 10,
  },
  button: {
    backgroundColor: green,
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  secondary: {
    backgroundColor: "#F3F6EF",
    borderWidth: 1,
    borderColor: "#DDE5D6",
  },
  buttonText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "#E1E6DB",
    backgroundColor: "#fff",
    borderRadius: 24,
  },
  chipActive: { backgroundColor: green, borderColor: green },
  chipText: { fontSize: 12, color: "#667261" },
  productGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    justifyContent: "space-between",
  },
  productCard: {
    borderWidth: 1,
    borderColor: "#E7EADF",
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#fff",
    marginBottom: 4,
  },
  productImage: { width: "100%", backgroundColor: "#E8EADF" },
  productBadge: {
    position: "absolute",
    left: 11,
    top: 12,
    backgroundColor: "#FFFFF4",
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 5,
  },
  organicText: { fontSize: 9, color: green, fontWeight: "600" },
  heart: {
    position: "absolute",
    right: 10,
    top: 10,
    backgroundColor: "#FFFFFFEA",
    width: 34,
    height: 34,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  tiny: { fontSize: 10, color: muted },
  productTitle: { fontSize: 15, fontWeight: "600", color: ink },
  price: { fontSize: 20, fontWeight: "700", color: ink },
  addButton: {
    borderWidth: 1,
    borderColor: "#C9D8BC",
    borderRadius: 7,
    backgroundColor: "#F1F6EB",
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  addText: { fontSize: 12, fontWeight: "700", color: green },
  bottomNote: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 30,
  },
  panel: {
    borderWidth: 1,
    borderColor: "#E4E9DE",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 22,
    marginBottom: 16,
    gap: 12,
  },
  cardTitle: { fontSize: 16, fontWeight: "600", color: ink },
  body: { fontSize: 14, color: "#5F6F60", lineHeight: 23 },
  subtitle: {
    fontSize: 14,
    color: muted,
    marginTop: 9,
    marginBottom: 25,
    lineHeight: 22,
  },
  stat: { fontSize: 32, fontWeight: "700", color: green },
  badge: {
    color: green,
    fontSize: 11,
    fontWeight: "600",
    backgroundColor: "#EDF4E6",
    padding: 8,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  empty: { padding: 40, alignItems: "center", gap: 15 },
  thumb: {
    height: 65,
    width: 65,
    borderRadius: 10,
    backgroundColor: "#E8EEDF",
  },
  mobileNav: {
    flexDirection: "row",
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 26 : 12,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderColor: "#E6EBE1",
  },
  mobileNavItem: { flex: 1, alignItems: "center", gap: 5 },
  scrim: {
    flex: 1,
    backgroundColor: "rgba(19,38,24,.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 18,
  },
  modal: {
    backgroundColor: "#FAFBF7",
    borderRadius: 22,
    padding: 24,
    width: "100%",
    maxHeight: "90%",
  },
  input: {
    borderWidth: 1,
    borderColor: "#DCE3D5",
    borderRadius: 9,
    padding: 13,
    color: ink,
    backgroundColor: "#fff",
    fontSize: 14,
  },
  cartLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderColor: "#E4E9DE",
  },
  quantity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 6,
    backgroundColor: "#EDF2E7",
    borderRadius: 8,
  },
  summary: {
    backgroundColor: "#EFF3E9",
    padding: 17,
    borderRadius: 12,
    marginVertical: 15,
    gap: 7,
  },
  toast: {
    position: "absolute",
    bottom: 90,
    left: "8%",
    right: "8%",
    backgroundColor: green,
    padding: 17,
    borderRadius: 12,
    alignItems: "center",
    zIndex: 1000,
  },
});
